### ISSUE TITLE
Implement patrol derived features in charcoal risk model

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/predictivemodelling#2]
Description of the features can be found in the slides from the winning team of the hackathon https://docs.google.com/presentation/d/1AyQwzvDUi3hIvoz3xRoc1jK2qQWKGIfQ/edit#slide=id.p7

**Comment by Mell-A** [comment]
We have two strategies that we can compare (running locally, not yet in the new repository)

- I have implemented a set of the features in R and use the random forest model
- @dkd58 is running the model of the winning team in python on the same set of features, it is from the darts package which can handle the temporal component of the data

**Comment by Mell-A** [comment]
The outcome on training data till 31 January 2024, and prediction for February 2024.

Insignificant difference between the two strategies so we could continue using the improved R model.

![Image](https://github.com/SensingClues/predictivemodelling/assets/50944991/a0c8a6fd-9a50-41a8-b615-11ffacf8fa28)
